Repository UniversityOfSaskatchewanCMPT371/term-project-2024-team-2, pull requests merged in 2024-02, with the labels that each got.

#84 #65 Add a basic dependency review step in CICD pipeline
  .github/workflows/build-react-app.yml
Labels: ID2

#70 63: Repository-wide .gitignore
  .gitignore
  .idea/.gitignore
  .idea/cmpt-371-team-2.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  my-webxr-app/.gitignore
Labels: enhancement, ID2

#98 68: Update Versions of checkout & setup-node actions to latest - v4
  .github/workflows/build-react-app.yml
Labels: CI/CD, ID2

#85 73: configure logging
  .gitignore
  my-webxr-app/.babelrc
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/src/log-config.tsx
  my-webxr-app/tests/error-and-above-log-config.test.tsx
  my-webxr-app/tests/info-and-above-log-config.test.tsx
Labels: ID2

#105 #104: Dependabot#1: Prototype Pollution in `lodash`
  my-webxr-app/package-lock.json
Labels: ID2

#101 100: Fixing jest testing that was not running as expected
  my-webxr-app/jest.config.js
  my-webxr-app/package-lock.json
  my-webxr-app/tests/error-and-above-log-config.test.tsx
  my-webxr-app/tests/info-and-above-log-config.test.tsx
  my-webxr-app/tsconfig.json
Labels: bug, ID2, test

#113 10: parse csv from filesystem
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/Box.tsx
  my-webxr-app/src/components/Button.tsx
  my-webxr-app/src/components/Floor.tsx
  my-webxr-app/src/components/LocalCsvReader.tsx
  my-webxr-app/src/components/RotatingBox.tsx
  my-webxr-app/src/components/TestButton.tsx
  my-webxr-app/tests/LocalCsvReader.test.tsx
Labels: Required, ID2

#112 11: parse csv from url
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/UrlCsvReader.tsx
  my-webxr-app/tests/UrlCsvReader.test.tsx
Labels: Required, ID2

#111 #78 Creating 3D Axis For Plotting Data Points
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/src/App.tsx
  my-webxr-app/src/Components/axis.tsx
  my-webxr-app/src/Components/createTicks.tsx
  my-webxr-app/src/Components/singleAxis.tsx
  my-webxr-app/tests/axis.test.tsx
  my-webxr-app/tsconfig.json
Labels: Required, ID2

#106 #79: Creating Data Points For 3D Graph
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/DataPoint.tsx
  my-webxr-app/src/components/DataPointMenu.tsx
  my-webxr-app/src/contexts/PointSelectionContext.tsx
  my-webxr-app/tests/DataPoint.test.tsx
Labels: Required, ID2

#125 #124 add parse url element back to App.tsx
  my-webxr-app/src/App.tsx
Labels: bug, ID2

#127 Add gherkin file
  Test/GherkinFeatureFiles/display-axis.feature
Labels: Gherkin, ID2, test

#126 #96 Add manual testing for displaying points in 3D space
  Test/GherkinFeatureFiles/display-points.feature
Labels: Gherkin, ID2, test

#129 #114: Add ID2 artifacts
  artifacts/id2/README.md
  artifacts/id2/id1_retro_jamboard.pdf
  artifacts/id2/id1_retro_review_planning_minutes.pdf
  artifacts/id2/id2_activity_log.pdf
  artifacts/id2/id2_class_diagram.pdf
  artifacts/id2/id2_code_template_report.pdf
  artifacts/id2/id2_component_diagram.pdf
  artifacts/id2/id2_dev_team_update.pdf
  artifacts/id2/id2_matthew_buglass_activity_log.pdf
  artifacts/id2/id2_requirements_specifications.pdf
  artifacts/id2/id2_risk_analysis.pdf
  artifacts/id2/id2_sequence_diagram.pdf
  artifacts/id2/id2_test_list.pdf
  artifacts/id2/id2_test_matrix.pdf
  artifacts/id2/id2_test_team_update.pdf
Labels: documentation, ID2

#131 Fixed a standup attendance
  artifacts/id2/README.md
Labels: documentation, ID2

#116 115: Test and Validate Development Work for ID 2
  .github/workflows/build-react-app.yml
  .github/workflows/deployment_prod.yml
  .github/workflows/deployment_staging.yml
  .github/workflows/main.yml
  .gitignore
  .idea/.gitignore
  .idea/cmpt-371-team-2.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  .noai
  Test/GherkinFeatureFiles/display-axis.feature
  Test/GherkinFeatureFiles/display-points.feature
  Test/GherkinFeatureFiles/importing-from-csv.feature
  Test/emptyCSV.csv
  Test/grades.csv
  artifacts/id2/README.md
  artifacts/id2/id1_retro_jamboard.pdf
  artifacts/id2/id1_retro_review_planning_minutes.pdf
  artifacts/id2/id2_activity_log.pdf
  artifacts/id2/id2_class_diagram.pdf
  artifacts/id2/id2_code_template_report.pdf
  artifacts/id2/id2_component_diagram.pdf
  artifacts/id2/id2_dev_team_update.pdf
  artifacts/id2/id2_matthew_buglass_activity_log.pdf
  artifacts/id2/id2_requirements_specifications.pdf
  artifacts/id2/id2_risk_analysis.pdf
  artifacts/id2/id2_sequence_diagram.pdf
  artifacts/id2/id2_test_list.pdf
  artifacts/id2/id2_test_matrix.pdf
  artifacts/id2/id2_test_team_update.pdf
  my-webxr-app/.babelrc
  my-webxr-app/.firebaserc
  my-webxr-app/.gitignore
  my-webxr-app/jest.config.js
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/src/App.tsx
  my-webxr-app/src/Components/axis.tsx
  my-webxr-app/src/Components/createTicks.tsx
  my-webxr-app/src/Components/singleAxis.tsx
  my-webxr-app/src/components/Box.tsx
  my-webxr-app/src/components/Button.tsx
  my-webxr-app/src/components/DataPoint.tsx
  my-webxr-app/src/components/DataPointMenu.tsx
  my-webxr-app/src/components/Floor.tsx
  my-webxr-app/src/components/LocalCsvReader.tsx
  my-webxr-app/src/components/RotatingBox.tsx
  my-webxr-app/src/components/TestButton.tsx
  my-webxr-app/src/components/UrlCsvReader.tsx
  my-webxr-app/src/contexts/PointSelectionContext.tsx
  my-webxr-app/src/log-config.tsx
  my-webxr-app/tests/DataPoint.test.tsx
  my-webxr-app/tests/LocalCsvReader.test.tsx
  my-webxr-app/tests/UrlCsvReader.test.tsx
  my-webxr-app/tests/axis.test.tsx
  my-webxr-app/tests/error-and-above-log-config.test.tsx
  my-webxr-app/tests/info-and-above-log-config.test.tsx
  my-webxr-app/tsconfig.json
Labels: ID2

#134 #133: PATCH: Duplicated components directories in ID2 production release
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/axis.tsx
  my-webxr-app/src/components/createTicks.tsx
  my-webxr-app/src/components/singleAxis.tsx
  my-webxr-app/tests/axis.test.tsx
Labels: bug, ID2

#141 #123: add write permission on pull request for prod-deployment job
  .github/workflows/main.yml
Labels: CI/CD, ID3

#150 #144: Clean up npm dependencies
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
Labels: enhancement

#149 #143: Remove support for Node.js 16
  .github/workflows/main.yml
Labels: enhancement, CI/CD

#146 #64: Create ESLint CI/CD
  .github/workflows/lint.yml
  my-webxr-app/.eslintrc.cjs
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/src/App.tsx
  my-webxr-app/src/LogConfig.tsx
  my-webxr-app/src/components/Axis.tsx
  my-webxr-app/src/components/Box.tsx
  my-webxr-app/src/components/Button.tsx
  my-webxr-app/src/components/CreateTicks.tsx
  my-webxr-app/src/components/DataPoint.tsx
  my-webxr-app/src/components/DataPointMenu.tsx
  my-webxr-app/src/components/Floor.tsx
  my-webxr-app/src/components/LocalCsvReader.tsx
  my-webxr-app/src/components/RotatingBox.tsx
  my-webxr-app/src/components/SingleAxis.tsx
  my-webxr-app/src/components/TestButton.tsx
  my-webxr-app/src/components/UrlCsvReader.tsx
  my-webxr-app/src/components/axis.tsx
  my-webxr-app/src/components/createTicks.tsx
  my-webxr-app/src/components/singleAxis.tsx
  my-webxr-app/src/contexts/PointSelectionContext.tsx
  my-webxr-app/src/log-config.tsx
  my-webxr-app/src/main.tsx
  my-webxr-app/tests/Axis.test.tsx
  my-webxr-app/tests/DataPoint.test.tsx
  my-webxr-app/tests/LocalCsvReader.test.tsx
  my-webxr-app/tests/UrlCsvReader.test.tsx
  my-webxr-app/tests/axis.test.tsx
  my-webxr-app/tests/error-and-above-log-config.test.tsx
  my-webxr-app/tests/info-and-above-log-config.test.tsx
  my-webxr-app/tests/sample.test.tsx
  my-webxr-app/tsconfig.json
Labels: CI/CD, ID3
