Repository UniversityOfSaskatchewanCMPT371/term-project-2024-team-2, pull requests merged in 2024-03, with the labels that each got.

#153 #26: UI interaction for point details
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/DataPoint.tsx
  my-webxr-app/src/components/DataPointMenu.tsx
  my-webxr-app/src/contexts/PointSelectionContext.tsx
  my-webxr-app/src/types/DataPointTypes.tsx
  my-webxr-app/tests/DataPoint.test.tsx
Labels: High Priority, ID3

#151 #22: create a Basic Column Repository
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/src/repository/Column.tsx
  my-webxr-app/src/repository/DataPoint.tsx
  my-webxr-app/src/repository/DbRepository.tsx
  my-webxr-app/src/repository/Repository.tsx
  my-webxr-app/tests/repository/DbRepository.test.tsx
Labels: ID3

#148 147 refactor csv reader
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/CsvReader.tsx
  my-webxr-app/src/components/LocalCsvReader.tsx
  my-webxr-app/src/components/UrlCsvReader.tsx
  my-webxr-app/src/utils/Assert.tsx
  my-webxr-app/src/utils/CsvUtils.tsx
  my-webxr-app/tests/CsvUtils.test.tsx
  my-webxr-app/tests/LocalCsvReader.test.tsx
  my-webxr-app/tests/UrlCsvReader.test.tsx
Labels: ID3

#136 24 backend for pca
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/src/App.tsx
  my-webxr-app/src/utils/PcaClassic.tsx
  my-webxr-app/src/utils/PcaCovariance.tsx
  my-webxr-app/src/utils/StandardizeDataset.tsx
  my-webxr-app/tests/PcaClassic.test.tsx
  my-webxr-app/tests/PcaCovariance.test.tsx
  my-webxr-app/tests/StandardizeDataset.test.tsx
  my-webxr-app/tests/sample.test.tsx
Labels: Required, High Priority, ID3

#156 13 data points in 3d space
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/Axis.tsx
  my-webxr-app/src/components/CreateTicks.tsx
  my-webxr-app/src/components/DataPoint.tsx
  my-webxr-app/src/components/Positions.tsx
  my-webxr-app/tests/3Dpoint-space.test.tsx
  my-webxr-app/vite.config.ts
Labels: Required, High Priority, ID3

#160 13: Fixed Aesha's features, just needed to adapt it to the vector return …
  my-webxr-app/src/components/DataPointMenu.tsx
Labels: bug, ID3

#157 #121 - Created gherkin file for #26
  Test/GherkinFeatureFiles/ui-interaction.feature
Labels: test, ID3, QA

#161 #118 Display integration gherkin
  Test/GherkinFeatureFiles/display-data-in-3D-space.feature
Labels: Gherkin, ID3

#165 154: Added the artifacts for the ID3 submission
  artifacts/id3/README.md
  artifacts/id3/id2_retro_jamboard.pdf
  artifacts/id3/id2_retro_minutes.pdf
  artifacts/id3/id3_activity_log.pdf
  artifacts/id3/id3_data_layer_abstraction_design.pdf
  artifacts/id3/id3_design_jam_minutes.pdf
  artifacts/id3/id3_requirements.pdf
  artifacts/id3/id3_risk_analysis.pdf
  artifacts/id3/id3_stakeholder_meeting_feb_15.pdf
  artifacts/id3/id3_stakeholder_meeting_feb_29.pdf
  artifacts/id3/id3_test_list.pdf
  artifacts/id3/id3_test_matrix.pdf
  artifacts/id3/id3_test_team_update.pdf
  artifacts/id3/imgs/data_hover.png
  artifacts/id3/imgs/data_select.png
  artifacts/id3/imgs/time_tracking.svg
Labels: documentation, ID3

#175 #169: Add eslint idea setting file to trigger eslint fix on save action
  .idea/jsLibraryMappings.xml
  .idea/jsLinters/eslint.xml
Labels: CI/CD

#181 Fixed bug in SingleAxis
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/GenerateXYZ.tsx
  my-webxr-app/src/components/SingleAxis.tsx
  my-webxr-app/tests/3Dpoint-space.test.tsx
  my-webxr-app/tests/Axis.test.tsx
Labels: bug

#177 176: Modify PCA backend to further match the requirements
  my-webxr-app/src/LogConfig.tsx
  my-webxr-app/src/utils/PcaClassic.tsx
  my-webxr-app/src/utils/PcaCovariance.tsx
  my-webxr-app/tests/PcaClassic.test.tsx
  my-webxr-app/tests/PcaCovariance.test.tsx
  my-webxr-app/tests/error-and-above-log-config.test.tsx
  my-webxr-app/tests/info-and-above-log-config.test.tsx
Labels: bug, ID4

#190 167: Add ID4 Artifacts
  artifacts/get_pdfs.sh
  artifacts/id4/README.md
  artifacts/id4/id3_retro_jamboard.pdf
  artifacts/id4/id3_retro_minutes.pdf
  artifacts/id4/id4_ativity_log.pdf
  artifacts/id4/id4_ativity_log_summary.pdf
  artifacts/id4/id4_data_abstraction_layer_update.pdf
  artifacts/id4/id4_dev_team_update.pdf
  artifacts/id4/id4_risk_plan.pdf
  artifacts/id4/id4_stakeholder_meeting_mar_14.pdf
  artifacts/id4/id4_stakeholder_meeting_mar_7.pdf
  artifacts/id4/id4_test_coverage.pdf
  artifacts/id4/id4_test_list.pdf
  artifacts/id4/id4_test_matrix.pdf
  artifacts/id4/id4_test_team_update.pdf
  artifacts/id4/id4_ui_refresh_3d_visualization.pdf
  artifacts/id4/id4_ui_refresh_modal_screens.pdf
  artifacts/id4/imgs/id4_DAL_update.jpg
  artifacts/id4/imgs/id4_activity_actual_vs_expected.svg
  artifacts/id4/imgs/id4_activity_pareto.svg
  artifacts/id4/imgs/id4_activity_timeline.svg
Labels: documentation, ID4

#192 #137 Create a method for running smoke tests on the system
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/CsvReader.tsx
  my-webxr-app/src/testing/TestHookWrite.tsx
  my-webxr-app/src/testing/TestHooksWork.test.tsx
  my-webxr-app/src/testing/TestingOptions.tsx
  my-webxr-app/src/testing/TextInFileSearch.tsx
  my-webxr-app/src/testing/TextInFileSearchtest.tsx
  my-webxr-app/src/testing/testLog.txt
Labels: test

#195 #193: Replace Jest with Vitest
  .gitignore
  my-webxr-app/.babelrc
  my-webxr-app/.eslintrc.cjs
  my-webxr-app/jest.config.js
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/src/testing/TestHookWrite.tsx
  my-webxr-app/src/testing/TextInFileSearch.test.tsx
  my-webxr-app/src/testing/TextInFileSearch.tsx
  my-webxr-app/tests/3Dpoint-space.test.tsx
  my-webxr-app/tests/Axis.test.tsx
  my-webxr-app/tests/CsvUtils.test.tsx
  my-webxr-app/tests/DataPoint.test.tsx
  my-webxr-app/tsconfig.json
  my-webxr-app/vite.config.ts
  my-webxr-app/vitest.setup.ts
Labels: bug, SPIKE, test

#214 213 fix z fighting
  my-webxr-app/src/components/DataPointMenu.tsx
Labels: ID5

#212 #204: Darken the UI
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/DataPoint.tsx
  my-webxr-app/src/components/DataPointMenu.tsx
  my-webxr-app/src/components/Floor.tsx
Labels: enhancement, ID5

#216 117 fix issue with drei in test
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/src/assets/sans-serif.normal.100.woff
  my-webxr-app/src/components/CreateTicks.tsx
  my-webxr-app/src/components/GenerateXYZ.tsx
  my-webxr-app/src/components/SingleAxis.tsx
  my-webxr-app/tests/3Dpoint-space.test.tsx
  my-webxr-app/tests/Axis.test.tsx
  my-webxr-app/tests/MockServer.tsx
  my-webxr-app/vitest.setup.ts
Labels: ID5

#215 163 implement the dal
  my-webxr-app/src/data/DataAbstractor.tsx
  my-webxr-app/src/data/DataLayer.tsx
  my-webxr-app/src/repository/Column.tsx
  my-webxr-app/src/repository/DbRepository.tsx
  my-webxr-app/src/repository/Repository.tsx
  my-webxr-app/src/utils/PcaCovariance.tsx
  my-webxr-app/tests/PcaCovariance.test.tsx
  my-webxr-app/tests/data/DataLayer.test.tsx
  my-webxr-app/tests/data/PrivilegedDataLayer.tsx
  my-webxr-app/tests/repository/DbRepository.test.tsx
Labels: Required, ID5

#219 218 fixing attributes
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/GraphingDataPoint.tsx
  my-webxr-app/src/components/GraphingDataPointMenu.tsx
  my-webxr-app/src/contexts/PointSelectionContext.tsx
  my-webxr-app/src/types/DataPointTypes.tsx
  my-webxr-app/tests/3Dpoint-space.test.tsx
  my-webxr-app/tests/DataPoint.test.tsx
Labels: bug, ID5

#226 164: Some refactor and cleanup in the DAL
  my-webxr-app/src/repository/DataPoint.tsx
  my-webxr-app/src/repository/DbRepository.tsx
  my-webxr-app/src/repository/Repository.tsx
  my-webxr-app/tests/repository/DbRepository.test.tsx
Labels: ID5

#222 164 hook up data point graphing to the dal
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/CreateGraphingDataPoints.tsx
  my-webxr-app/src/components/GraphingDataPoint.tsx
  my-webxr-app/src/components/Positions.tsx
  my-webxr-app/src/data/DataAbstractor.tsx
  my-webxr-app/src/data/DataLayer.tsx
  my-webxr-app/src/repository/Column.tsx
  my-webxr-app/src/repository/DbRepository.tsx
  my-webxr-app/src/repository/Repository.tsx
  my-webxr-app/src/types/DataPointTypes.tsx
  my-webxr-app/tests/components/3Dpoint-space.test.tsx
  my-webxr-app/tests/components/CreateGraphingDataPoints.test.tsx
  my-webxr-app/tests/components/GraphingDataPoint.test.tsx
  my-webxr-app/tests/components/SingleAxis.test.tsx
  my-webxr-app/tests/data/DataLayer.test.tsx
  my-webxr-app/tests/repository/DbRepository.test.tsx
  my-webxr-app/tests/utils/CsvUtils.test.tsx
  my-webxr-app/tests/utils/PcaCovariance.test.tsx
  my-webxr-app/tests/utils/StandardizeDataset.test.tsx
Labels: Required, ID5

#231 #204: redo dark UI + place billboard behind axis
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/Floor.tsx
  my-webxr-app/src/components/GraphingDataPoint.tsx
  my-webxr-app/src/components/GraphingDataPointMenu.tsx
Labels: ID5

#232 #225: DataLayer tests are using the same database concurrently
  my-webxr-app/src/data/DataLayer.tsx
  my-webxr-app/tests/data/DataLayer.test.tsx
  my-webxr-app/tests/data/PrivilegedDataLayer.tsx
  my-webxr-app/vitest.setup.ts
Labels: bug, test, ID5

#186 #122: Vite and log4js incompatibility
  .github/workflows/deployment_prod.yml
  .github/workflows/deployment_staging.yml
  my-webxr-app/.env.local.template
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/GraphingDataPoint.tsx
  my-webxr-app/src/contexts/PointSelectionContext.tsx
  my-webxr-app/src/utils/LoggingUtils.tsx
  my-webxr-app/src/utils/PcaCovariance.tsx
  my-webxr-app/tests/components/3Dpoint-space.test.tsx
  my-webxr-app/tests/components/CreateGraphingDataPoints.test.tsx
  my-webxr-app/tests/components/GraphingDataPoint.test.tsx
  my-webxr-app/tests/repository/DbRepository.test.tsx
  my-webxr-app/vitest.setup.ts
Labels: bug, Required, ID3, ID4, ID5

#234 200 SmokeTest for reading a csv
  .gitignore
  my-webxr-app/package.json
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/CsvReader.tsx
  my-webxr-app/src/smoketest/ImportingFromCSV.test.tsx
  my-webxr-app/src/smoketest/TestHookWrite.tsx
  my-webxr-app/src/smoketest/TestHooksWorktest.tsx
  my-webxr-app/src/smoketest/TestingOptions.tsx
  my-webxr-app/src/smoketest/TextInFileSearch.tsx
  my-webxr-app/src/smoketest/TextInFileSearchtest.tsx
  my-webxr-app/src/smoketest/testLog.txt
  my-webxr-app/src/testing/testLog.txt
Labels: test, ID5

#238 237 assert is not a function bug
  my-webxr-app/vite.config.ts
Labels: bug

#142 #132: Deploy to Firebase production action failed to trigger
  .github/workflows/build_and_test.yml
  .github/workflows/deployment_dev.yml
  .github/workflows/deployment_prod.yml
  .github/workflows/deployment_staging.yml
  .github/workflows/main.yml
Labels: bug, CI/CD, ID3, ID4, ID5

#223 182: Declare Pre- and Post-Conditions on existing code
  .idea/inspectionProfiles/Project_Default.xml
  my-webxr-app/src/components/Box.tsx
  my-webxr-app/src/components/Button.tsx
  my-webxr-app/src/components/CreateGraphingDataPoints.tsx
  my-webxr-app/src/components/CreateTick.tsx
  my-webxr-app/src/components/CsvReader.tsx
  my-webxr-app/src/components/Floor.tsx
  my-webxr-app/src/components/GenerateXYZ.tsx
  my-webxr-app/src/components/GraphingDataPoint.tsx
  my-webxr-app/src/components/GraphingDataPointMenu.tsx
  my-webxr-app/src/components/Positions.tsx
  my-webxr-app/src/components/RotatingBox.tsx
  my-webxr-app/src/components/SingleAxis.tsx
  my-webxr-app/src/components/TestButton.tsx
  my-webxr-app/src/contexts/PointSelectionContext.tsx
  my-webxr-app/src/data/DataLayer.tsx
  my-webxr-app/src/repository/Column.tsx
  my-webxr-app/src/repository/DataPoint.tsx
  my-webxr-app/src/repository/DbRepository.tsx
  my-webxr-app/src/repository/Repository.tsx
  my-webxr-app/src/smoketest/TestHookWrite.tsx
  my-webxr-app/src/smoketest/TestingOptions.tsx
  my-webxr-app/src/smoketest/TextInFileSearch.tsx
  my-webxr-app/src/utils/Assert.tsx
  my-webxr-app/src/utils/CsvUtils.tsx
  my-webxr-app/src/utils/PcaCovariance.tsx
  my-webxr-app/src/utils/StandardizeDataset.tsx
Labels: documentation, ID5

#224 #20: add a slider to let user choose the graph scale. add all graph c…
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/CreateTick.tsx
  my-webxr-app/src/components/ScaleSlider.tsx
  my-webxr-app/tests/components/CreateTicks.test.tsx
  my-webxr-app/tests/components/GenerateXYZ.test.tsx
  my-webxr-app/tests/components/ScaleSlider.test.tsx
  my-webxr-app/tests/components/SingleAxis.test.tsx
Labels: ID5

#243 #241: Fix Staging Deployment
  .github/workflows/deployment_prod.yml
  .github/workflows/deployment_staging.yml
Labels: bug, ID5

#245 #241: Fix Staging Deployment (Attempt 2)
  .github/workflows/build_and_test.yml
Labels: bug, ID5

#174 #15 - Implementing Axis Selection
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/CreateGraphingDataPoints.tsx
  my-webxr-app/src/components/SelectAxesMenu.tsx
  my-webxr-app/src/contexts/AxesSelectionContext.tsx
  my-webxr-app/src/data/DataAbstractor.tsx
  my-webxr-app/src/data/DataLayer.tsx
  my-webxr-app/src/repository/DbRepository.tsx
  my-webxr-app/src/repository/Repository.tsx
  my-webxr-app/tests/components/CreateGraphingDataPoints.test.tsx
  my-webxr-app/tests/data/DataLayer.test.tsx
  my-webxr-app/tests/repository/DbRepository.test.tsx
Labels: ID4, ID5

#240 239 axis scale with data
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/CreateGraphingDataPoints.tsx
  my-webxr-app/src/components/CreatePointPositions.tsx
  my-webxr-app/src/components/GenerateTick.tsx
  my-webxr-app/src/components/GenerateXYZ.tsx
  my-webxr-app/src/components/Positions.tsx
  my-webxr-app/src/components/SingleAxis.tsx
  my-webxr-app/src/contexts/AxesSelectionContext.tsx
  my-webxr-app/src/data/DataAbstractor.tsx
  my-webxr-app/src/data/DataLayer.tsx
  my-webxr-app/src/repository/DbRepository.tsx
  my-webxr-app/src/repository/Repository.tsx
  my-webxr-app/tests/components/CreatePointPositions.test.tsx
  my-webxr-app/tests/components/GenerateTicks.test.tsx
  my-webxr-app/tests/components/GenerateXYZ.test.tsx
  my-webxr-app/tests/components/SingleAxis.test.tsx
  my-webxr-app/tests/repository/DbRepository.test.tsx
Labels: bug, High Priority, ID5

#191 #162:CSV-to-DAL
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/CreateGraphingDataPoints.tsx
  my-webxr-app/src/components/CsvReader.tsx
  my-webxr-app/src/data/DataAbstractor.tsx
  my-webxr-app/src/data/DataLayer.tsx
  my-webxr-app/src/repository/DbRepository.tsx
  my-webxr-app/src/repository/Repository.tsx
  my-webxr-app/src/utils/CsvUtils.tsx
  my-webxr-app/src/utils/LoggingUtils.tsx
  my-webxr-app/tests/utils/CsvUtils.test.tsx
Labels: Required, ID4, ID5

#242 197 writing smoke test that verifies the axis are on the page
  my-webxr-app/src/components/GenerateXYZ.tsx
  my-webxr-app/src/smoketest/displayAxis.test.tsx
Labels: test, ID5
