Repository UniversityOfSaskatchewanCMPT371/term-project-2024-team-2, pull requests merged in 2024-04, with the labels that each got.

#253 252 bug assert is used without being imported and csvurlreader doesnt calculate stats and pca upon loading file
  my-webxr-app/src/utils/CsvUtils.tsx
Labels: bug, ID5

#250 249 fix hard coded point scale factor
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/CreateGraphingDataPoints.tsx
  my-webxr-app/src/components/CreatePointPositions.tsx
  my-webxr-app/src/components/GenerateXYZ.tsx
  my-webxr-app/src/components/SelectAxesMenu.tsx
  my-webxr-app/tests/components/CreateGraphingDataPoints.test.tsx
  my-webxr-app/tests/components/GenerateXYZ.test.tsx
Labels: bug, ID5

#254 #248: create a Reload state to trigger reloading SelectAxesMenu.tsx e…
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/CsvReader.tsx
  my-webxr-app/src/components/SelectAxesMenu.tsx
  my-webxr-app/src/data/DataLayer.tsx
  my-webxr-app/src/utils/CsvUtils.tsx
  my-webxr-app/tests/components/SelectAxesMenu.test.tsx
  my-webxr-app/tests/utils/CsvUtils.test.tsx
Labels: bug, ID5

#235 199 smoke test for display points gherkin
  my-webxr-app/src/components/GraphingDataPoint.tsx
  my-webxr-app/src/contexts/PointSelectionContext.tsx
  my-webxr-app/src/smoketest/DisplayPointsSmokeTest.test.tsx
Labels: test, ID5

#261 #203: Add testing utils to display loaded data
  my-webxr-app/src/smoketest/TestingOptions.tsx
Labels: test, ID5

#262 #259 - re-implement smoke test for importing csv, was deleted from CS…
  my-webxr-app/src/components/CsvReader.tsx
  my-webxr-app/src/smoketest/ImportingFromCSV.test.tsx
Labels: bug

#258 198 smoke test for display data in 3d space
  my-webxr-app/src/components/GraphingDataPointMenu.tsx
  my-webxr-app/src/smoketest/DisplayData3DSpace.test.tsx
Labels: test, ID5

#265 #119: Write gherkin + smoketest for data exclusion
  .gitignore
  Test/GherkinFeatureFiles/data-exclusion.feature
  Test/exclusion.csv
  my-webxr-app/package.json
  my-webxr-app/smoketests/DataExclusion.test.tsx
  my-webxr-app/smoketests/DisplayData3DSpace.test.tsx
  my-webxr-app/smoketests/DisplayPointsSmokeTest.test.tsx
  my-webxr-app/smoketests/ImportingFromCSV.test.tsx
  my-webxr-app/smoketests/TestHookWrite.tsx
  my-webxr-app/smoketests/TestHooksWorktest.tsx
  my-webxr-app/smoketests/TestingOptions.tsx
  my-webxr-app/smoketests/TextInFileSearch.tsx
  my-webxr-app/smoketests/TextInFileSearchtest.tsx
  my-webxr-app/smoketests/displayAxis.test.tsx
  my-webxr-app/smoketests/testLog.txt.template
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/CsvReader.tsx
  my-webxr-app/src/components/GenerateXYZ.tsx
  my-webxr-app/src/components/GraphingDataPoint.tsx
  my-webxr-app/src/components/GraphingDataPointMenu.tsx
  my-webxr-app/src/contexts/PointSelectionContext.tsx
  my-webxr-app/src/smoketest/testLog.txt
  my-webxr-app/src/utils/CsvUtils.tsx
  my-webxr-app/tsconfig.json
Labels: Gherkin, test, ID3, ID4, ID5

#266 #201: Write smoke test for UI interaction gherkin
  Test/box.csv
  my-webxr-app/smoketests/UiInteraction.test.tsx
  my-webxr-app/src/components/GraphingDataPointMenu.tsx
Labels: test, ID5

#268 #267: Investigate if environment variables are being included in firebase deployment
  .github/workflows/deployment_dev.yml
  .github/workflows/deployment_prod.yml
  .github/workflows/deployment_staging.yml
Labels: CI/CD, ID5

#270 #263 - created smoke tests for axis selection
  my-webxr-app/smoketests/AxisSelection.test.tsx
  my-webxr-app/src/components/SelectAxesMenu.tsx
Labels: test, ID5

#273 #272 - visible test case not needed as the other test cases test that…
  my-webxr-app/smoketests/ScalingBar.test.tsx
Labels: bug, test, ID5

#276 #275 - refactor menu datapoint to display additonal column values
  my-webxr-app/src/components/CreateGraphingDataPoints.tsx
  my-webxr-app/src/components/CsvReader.tsx
  my-webxr-app/src/components/GraphingDataPoint.tsx
  my-webxr-app/src/components/GraphingDataPointMenu.tsx
  my-webxr-app/src/components/SelectAxesMenu.tsx
  my-webxr-app/src/contexts/AxesSelectionContext.tsx
  my-webxr-app/src/data/DataAbstractor.tsx
  my-webxr-app/src/data/DataLayer.tsx
  my-webxr-app/src/repository/DataPoint.tsx
  my-webxr-app/src/repository/DbRepository.tsx
  my-webxr-app/src/repository/Repository.tsx
  my-webxr-app/src/types/DataPointTypes.tsx
  my-webxr-app/src/utils/CsvUtils.tsx
  my-webxr-app/tests/components/CreateGraphingDataPoints.test.tsx
  my-webxr-app/tests/components/CreatePointPositions.test.tsx
  my-webxr-app/tests/components/GenerateXYZ.test.tsx
  my-webxr-app/tests/components/SelectAxesMenu.test.tsx
Labels: ID6

#282 278 navigate in vr space
  my-webxr-app/src/App.tsx
  my-webxr-app/src/components/CameraMovement.tsx
Labels: ID6

#284 283 modify naviagtion relative to camera direction
  my-webxr-app/src/components/CameraMovement.tsx
Labels: ID6
