Repository UniversityOfSaskatchewanCMPT371/term-project-2024-team-2, pull requests merged in 2024-01, with the labels that each got.

#48 6 web xr spike
  my-webxr-app/.eslintrc.cjs
  my-webxr-app/.firebase/hosting.YnVpbGQ.cache
  my-webxr-app/.firebase/hosting.ZGlzdA.cache
  my-webxr-app/.firebaserc
  my-webxr-app/.gitignore
  my-webxr-app/README.md
  my-webxr-app/build/404.html
  my-webxr-app/build/index.html
  my-webxr-app/firebase.json
  my-webxr-app/index.html
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/public/vite.svg
  my-webxr-app/src/App.css
  my-webxr-app/src/App.tsx
  my-webxr-app/src/Components/Box.tsx
  my-webxr-app/src/Components/Button.tsx
  my-webxr-app/src/Components/Floor.tsx
  my-webxr-app/src/Components/RotatingBox.tsx
  my-webxr-app/src/Components/TestButton.tsx
  my-webxr-app/src/assets/react.svg
  my-webxr-app/src/index.css
  my-webxr-app/src/main.tsx
  my-webxr-app/src/styles.css
  my-webxr-app/src/vite-env.d.ts
  my-webxr-app/tsconfig.json
  my-webxr-app/tsconfig.node.json
  my-webxr-app/vite.config.ts
Labels: SPIKE, ID1

#40 Created file for LICENSE
  LICENSE
Labels: ID1

#38 Initial README.md
  README.md
Labels: ID1

#50 49: Added a PR Template
  .github/pull_request_template.md
Labels: CI/CD, ID1

#47 Add GH Actions workflow to build React app
  .github/workflows/build-react-app.yml
  my-webxr-app/src/App.tsx
  my-webxr-app/src/Components/Button.tsx
  my-webxr-app/src/Components/RotatingBox.tsx
Labels: CI/CD, ID1

#58 45: Adding file Artifacts for ID 1
  artifacts/id1/Architecture Design Records (ADRs) ID1.pdf
  artifacts/id1/Branching Strategy.pdf
  artifacts/id1/Risk Assesment - ID1.pdf
  artifacts/id1/Risk Plan.pdf
  artifacts/id1/UI Prototype.pdf
Labels: documentation, ID1

#56 ID1: Release Candidate
  .github/pull_request_template.md
  .github/workflows/build-react-app.yml
  LICENSE
  README.md
  Test/GherkinFeatureFiles/webxr-spike.feature
  artifacts/id1/Architecture Design Records (ADRs) ID1.pdf
  artifacts/id1/Branching Strategy.pdf
  artifacts/id1/QA Test Results - ID1.pdf
  artifacts/id1/Risk Assesment - ID1.pdf
  artifacts/id1/Risk Plan.pdf
  artifacts/id1/UI Prototype.pdf
  my-webxr-app/.eslintrc.cjs
  my-webxr-app/.firebase/hosting.YnVpbGQ.cache
  my-webxr-app/.firebase/hosting.ZGlzdA.cache
  my-webxr-app/.firebaserc
  my-webxr-app/.gitignore
  my-webxr-app/README.md
  my-webxr-app/build/404.html
  my-webxr-app/build/index.html
  my-webxr-app/firebase.json
  my-webxr-app/index.html
  my-webxr-app/package-lock.json
  my-webxr-app/package.json
  my-webxr-app/public/vite.svg
  my-webxr-app/src/App.css
  my-webxr-app/src/App.tsx
  my-webxr-app/src/Components/Box.tsx
  my-webxr-app/src/Components/Button.tsx
  my-webxr-app/src/Components/Floor.tsx
  my-webxr-app/src/Components/RotatingBox.tsx
  my-webxr-app/src/Components/TestButton.tsx
  my-webxr-app/src/assets/react.svg
  my-webxr-app/src/index.css
  my-webxr-app/src/main.tsx
  my-webxr-app/src/styles.css
  my-webxr-app/src/vite-env.d.ts
  my-webxr-app/tests/sample.test.tsx
  my-webxr-app/tsconfig.json
  my-webxr-app/tsconfig.node.json
  my-webxr-app/tsconfig.prod.json
  my-webxr-app/vite.config.ts
Labels: ID1

#82 #66: Add a build step to run jest unit tests
  .github/workflows/build-react-app.yml
Labels: ID2

#81 #69: Remove the build trigger on push event
  .github/workflows/build-react-app.yml
Labels: ID2
